language: go

go:
  - 1.8
  - 1.7
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/go-yaml/yaml
  - go get github.com/immortal/logrotate
  - go get github.com/immortal/multiwriter
  - go get github.com/immortal/natcasesort
  - go get github.com/immortal/xtime
  - go get github.com/mattn/goveralls
  - go get github.com/nbari/violetear
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
